### ISSUE TITLE
third party extension support

### ISSUE THREAD

**Issue by StoneSoldier** [Kakifrucht/flarum-de#14]
Sollen wir die Übersetzungen von third Party Extensions ins Language pack oder
 in die einzelnen Extensions tun?

**Comment by Kakifrucht** [comment]
Gute Frage, wenn ich mir andere Projekte anschaue, dann scheinen diese durchaus auch

**Comment by Kakifrucht** [comment]
Gute Frage, wenn ich mir andere Projekte anschaue, dann scheinen diese durchaus zT auch nicht gebundlete extensions mit einzubegreifen.
Das bedeutet dann aber natürlich auch, dass diese unterhalten werden müssten. 

Mein Votum: Es bei den zentralen zu belassen. Ich denke schon, dass sich die Entwickler darüber freuen würden die Übersetzungen direkt bei sich mitzuliefern.

**Comment by StoneSoldier** [comment]
Seh ich auch so.

**Comment by OddDev** [comment]
I think that paradigm will not work on the long-run since Friends of Flarum decided to put the language packs responsible to translate stuff. 
https://github.com/FriendsOfFlarum/links/pull/13#issuecomment-532831880
https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack

Currently, I'm not able to commit to the third-party extension nor to the language pack. My only option is to install FoF/linguist and translate everything manually decentralised.

**Comment by luceos** [comment]
There are a few options:

- fork this language pack into one that supports more extensions, fragmenting translation efforts for the German language
- stick to (what I think is a great option) core extensions for one language pack and create another one for third party extensions
- create a local extender to load your custom translation files for your specific installation (better than using linguist)
- join this initiative https://discuss.flarum.org/d/20807

**Comment by Kakifrucht** [comment]
I just went through the given options and my preference is probably to add another extension/repository just for third party plugins. It seems like the cleanest approach and adds a nice centralized repository to collect all translations to. But I'm not sure if one language can trivially fetch translations from two extensions, or does this work out of the box when simply enabling the 'flarum-de-extended' (or similiar) extension, without having it register as an additional language?

rob006's approach looks interesting, but given that my workflow to update flarum-de for the core extensions is already very simple, I would rather not add additional complexity/dependency on top of it. It definitely might make sense for a potential flarum-de-extended extension!

**Comment by luceos** [comment]
@Kakifrucht I recently gave a spin to a recent pilot similar to the one rob006 has, feel free to chat me up on discord. It's not yet part of the flarum organisation, but really well on its way to be and we could use a reliable translator for German.

It also splits core vs third party extensions and uses lokalise in the background:

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/504687/65806911-4b821c80-e18c-11e9-9586-04cbe24c3e7b.png">

**Comment by Kakifrucht** [comment]
Looks like a great idea to centralize it this way imo, certainly interested in helping out! I wasn't able to message you on Discord for some reason.

**Comment by luceos** [comment]
Add me as a friend first. I will accept asap.

**Comment by OddDev** [comment]
Also sent you one. Count me in :)

**Comment by luceos** [comment]
@OddDev didn't get one Kai..

**Comment by Kakifrucht** [comment]
I have setup a [flarum-de-extended](https://github.com/Kakifrucht/flarum-de-extended) repository with support for a couple extensions that I use. Please PR whichever extensions you would like to have added!
