### ISSUE TITLE
Make it compatible with beta 14?

### ISSUE THREAD

**Issue by HLFH** [Kakifrucht/flarum-de#27]
Hi,

Any plans to make it compatible with beta 14?
It is currently compatible with beta 13: https://github.com/Kakifrucht/flarum-de#compatibility.

Thanks,
HLFH

**Comment by dartrax** [comment]
I was just about asking the same ;-)

**Comment by Kakifrucht** [comment]
Absolutely, my plan was to update once I can update my own forum, however a couple of extensions are still not updated, and beta 14 was a breaking update that broke most extensions.

If you can't wait, you can find the updated strings [here](https://github.com/flarum/lang-english/compare/v0.1.0-beta.13...v0.1.0-beta.14.1), feel free to PR them. I don't want to give any specific timeframes right now, but I'll get to it soonish.

**Comment by Kakifrucht** [comment]
We are now beta 14 compatible!
