### ISSUE TITLE
Fehlerhafte Anzeige der Texte

### ISSUE THREAD

**Issue by ProfessorVarox** [Kakifrucht/flarum-de#28]
Liebes Team, erstmal einen großen Dank, dass ihr euch die Mühe gemacht habt, Flarum zu übersetzen.

Ich habe gerade eben die Extension erfolgreich mit Composer installiert, aber wenn ich diese auswähle, werden alle Texte fehlerhaft angezeigt
![Hier ist ein Bild](https://share.professorvarox.xyz/caYO8/WusAPegE51.png/raw)

In den "Basic" Einstellungen kann ich auch nirgends die Sprache auswählen
![Hier das Bild dazu](https://share.professorvarox.xyz/caYO8/NEbogIKi64.png/raw)

# Infos zum System:
PHP: 7.4.12
Flarum: 0.1.0-beta.14.1
MySQL: 10.3.25-MariaDB-0+deb10u1
Server: Plesk

Ansonsten habe ich auch nirgends irgendwelche Fehlermeldungen gefunden

**Comment by Kakifrucht** [comment]
Du scheinst eine sehr alte Version installiert zu haben (0.1.11), versuche nochmal ein update.
Wenn nur eine Sprache ausgewählt ist erscheint das Sprach Auswahlmenü nicht.

**Comment by ProfessorVarox** [comment]
Vielen Dank, nach einem Update der Erweiterung klappt alles
