### ISSUE TITLE
Falsche Schreibweise von markieren in core.yml

### ISSUE THREAD

**Issue by robinheidrich** [Kakifrucht/flarum-de#29]
Es wird "makieren" statt "markieren" benutzt bei "[Als gelesen makieren](https://github.com/Kakifrucht/flarum-de/blob/ee9ed874cf6202d3202a6b559cc5fb4c7028031f/locale/core.yml#L287)" und "[Alle als gelesen makieren](https://github.com/Kakifrucht/flarum-de/blob/ee9ed874cf6202d3202a6b559cc5fb4c7028031f/locale/core.yml#L617)".

**Comment by Kakifrucht** [comment]
In der Tat, ich danke dir. Ist im nächsten release für Flarum 1.0 gefixt.
