### ISSUE TITLE
Trotz Aktivierung keine deutsche Übersetzung

### ISSUE THREAD

**Issue by nsauter** [Kakifrucht/flarum-de#31]
Hi!

Ich habe mir eben testweise ein Flarum installiert (Neuste Version die mit composer kommt) und daraufhin mit 

`composer require kakifrucht/flarum-de`

das Language Pack installiert. Daraufhin in der Admin GUI das Englische Pack deaktiviert und das deutsche aktiviert. Trotzdem hab ich keine deutsche Übersetzung. Hab ich was vergessen? Ist das Pack kompatibel?

**Comment by nsauter** [comment]
Nevermind, sorry. Scheinbar muss man das als User (wenn man noch unter Englischen Settings eingeloggt war) selbst, wenn nur noch ein Language Pack aktiv ist nochmals extra setzen.

**Comment by Kakifrucht** [comment]
Die Englische Übersetzung braucht gar nicht deaktiviert zu sein, ich empfehle stattdessen beide aktiv zu lassen, Deutsch unter Grundeinstellungen als Standard auszuwählen und das Sprach Auswahlmenü auszublenden.
